# Generated by Django 4.0.4 on 2022-06-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateTimeField()),
                ('text', models.TextField(max_length=250)),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
